# Install the dependencies using bundler

In [13]:
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
    
  gem 'daru', '~> 0.3'
  gem 'daru-view', '~> 0.2.6'
  gem "nyaplot"
  gem 'matrix', '~> 0.4.2'
  gem 'geocoder'
  gem 'gpx'
end
require 'daru'
require 'daru/view'

false

# Analize a foil session

In [4]:
require_relative 'foil_activity_analyzer'

file = 'activities/2024-06-17_2.gpx'
lift_speed = 12
fa = FoilActivityAnalyzer.new(file, lift_speed)
df = fa.data_frame
df.head(10)
df[:distance_m].replace_values(0, 0.000000001)
df[:distance_cumsum_m] = df[:distance_m].cumsum
df.head 5

#<Daru::DataFrame(5x9)>
                           timestamp               lat               lon                hr      ellapsed_sec        distance_m         speed_m_s distance_cumsum_m           on_foil
                 0 2024-06-15 11:22: 52.46734491549432  5.33144898712635                97               0.0           1.0e-09               0.0           1.0e-09                 0
                 1 2024-06-15 11:22: 52.46731549501419   5.3314343187958                98               2.0 3.418985235444624              1.71 3.418985236444624                 0
                 2 2024-06-15 11:22: 52.46731985360384 5.331416800618172                98               3.0 1.281859287771472              0.43 4.700844524216096                 0
                 3 2024-06-15 11:22: 52.46731708757579 5.331427529454231                99               2.0 0.789188250367781              0.39 5.490032774583877                 0
                 4 2024-06-15 11:22: 52.46731205843389 5.331429373472929                98               1.0 0.572997070084482              0.57 6.063029844668359                 0

Lehet az adatokat ido es tavolsag alapjan indexelni, de nem igazan tudom hogy mire jo az index

[Basic time seriies index](https://nbviewer.org/github/SciRuby/sciruby-notebooks/blob/master/Data%20Analysis/Basic%20Time%20Series.ipynb)

In [5]:
df.set_index(:timestamp, keep: true)
# df.set_index(:distance_cumsum_m, keep: true)
df.head 5

#<Daru::DataFrame(5x9)>
                           timestamp               lat               lon                hr      ellapsed_sec        distance_m         speed_m_s distance_cumsum_m           on_foil
 2024-06-15 11:22: 2024-06-15 11:22: 52.46734491549432  5.33144898712635                97               0.0           1.0e-09               0.0           1.0e-09                 0
 2024-06-15 11:22: 2024-06-15 11:22: 52.46731549501419   5.3314343187958                98               2.0 3.418985235444624              1.71 3.418985236444624                 0
 2024-06-15 11:22: 2024-06-15 11:22: 52.46731985360384 5.331416800618172                98               3.0 1.281859287771472              0.43 4.700844524216096                 0
 2024-06-15 11:22: 2024-06-15 11:22: 52.46731708757579 5.331427529454231                99               2.0 0.789188250367781              0.39 5.490032774583877                 0
 2024-06-15 11:22: 2024-06-15 11:22: 52.46731205843389 5.331429373472929                98               1.0 0.572997070084482              0.57 6.063029844668359                 0

In [16]:
df.plot(type: :line, x: :distance_cumsum_m, y: :speed_m_s) do |p, d|
  p.x_label 'Distance'
  p.y_label 'Speed'
end

#<Nyaplot::Plot:0x0000004056639278 @properties={:diagrams=>[#<Nyaplot::Diagram:0x0000004055e019c0 @properties={:type=>:line, :options=>{:x=>:distance_cumsum_m, :y=>:speed_m_s}, :data=>"a5b41e81-5ce1-4150-bacc-7c6e9a09a5b3"}, @xrange=[0.0, 23686.57035350084], @yrange=[0.0, 14.75]>], :options=>{:x_label=>"Distance", :y_label=>"Speed", :zoom=>true, :width=>700, :xrange=>[0.0, 23686.57035350084], :yrange=>[0.0, 14.75]}}>

## Analyzing an activity

In [9]:
require 'daru/view'
file = "activities/2024-07-06-wing.gpx"
  fa = FoilActivityAnalyzer.new(file, lift_speed = 15)
  df = fa.data_frame
  dist = df[:distance_cumsum_m]
  speed = df[:speed_m_s] * 3.6
  # line = speed.rolling_mean
  on_foil = df[:on_foil]
  line_graph = Daru::View::Plot.new(
    [
      { type: :area, name: 'On foil', data: dist.to_a.zip((on_foil * speed.max).to_a), showInLegend: false },
      { type: :line, name: 'Speed', data: dist.to_a.zip(speed.to_a) }
      # { type: :line, name: 'HR', data: dist.to_a.zip(df[:hr].to_a) }
      # { type: :line, name: 'Speed AVG', data: dist.to_a.zip(speed.rolling_mean(5).to_a) }
    ],
    title: { text: nil },
    xAxis: [{ title: { text: 'Distance (m)' } }],
    yAxis: [{ title: { text: 'Speed (km/h)' } }],
    tooltip: { enabled: false },
    legend: { enabled: false },
    adapter: :highcharts
  )
line_graph.show_in_iruby

"\n\nvar event = document.createEvent(\"HTMLEvents\");\nevent.initEvent(\"load_highcharts\", false, false);\nwindow.dispatchEvent(event);\nconsole.log(\"Finish loading highchartsjs\");\n"

"              <script type=\"text/javascript\">\n        $(function() {\n\n                var options = { \"title\": { \"text\": null },\"xAxis\": [ { \"title\": { \"text\": \"Distance (m)\" } } ],\"yAxis\": [ { \"title\": { \"text\": \"Speed (km/h)\" } } ],\"tooltip\": { \"enabled\": false },\"legend\": { \"enabled\": false },\"chart\": { \"renderTo\": \"qxlrezsdyth\" },\"series\": [{ \"type\": \"area\",\"name\": \"On foil\",\"data\": [ [ 0.0,0.0 ],[ 1.0581704783339276,0.0 ],[ 4.3969571966098515,0.0 ],[ 13.058801020741278,0.0 ],[ 19.383448050138703,0.0 ],[ 24.71719791624368,0.0 ],[ 27.816964400250917,0.0 ],[ 33.18039089965177,0.0 ],[ 36.7871938954114,0.0 ],[ 40.263081472114024,0.0 ],[ 48.52349977801874,0.0 ],[ 52.59661432178439,0.0 ],[ 65.43699557200249,0.0 ],[ 69.82087917309457,0.0 ],[ 80.11121741946276,0.0 ],[ 85.61826883507155,0.0 ],[ 91.40755949089724,0.0 ],[ 107.28512657435681,0.0 ],[ 117.18495320198339,53.1 ],[ 127.35040682235697,53.1 ],[ 133.3025452515731,53.1 ],[ 138.09687885518952,53.1 ],[ 143.13513391261563,53.1 ],[ 152.95458216175652,53.1 ],[ 163.27210727572768,53.1 ],[ 173.72773771975125,53.1 ],[ 186.33153346835076,53.1 ],[ 196.734228144236,53.1 ],[ 201.4992114049383,53.1 ],[ 206.03797647596662,53.1 ],[ 216.51015399327193,53.1 ],[ 221.94960724027828,53.1 ],[ 231.34037914253315,53.1 ],[ 246.27988894371884,53.1 ],[ 277.5247324956651,53.1 ],[ 282.1863211349932,53.1 ],[ 302.35894122397355,53.1 ],[ 308.6361517868814,53.1 ],[ 313.0645224423872,53.1 ],[ 319.3053707672554,53.1 ],[ 330.88506695440446,53.1 ],[ 335.9228611158278,53.1 ],[ 345.72086339570444,53.1 ],[ 352.10470322531296,53.1 ],[ 363.81024684311694,53.1 ],[ 370.7552485310872,53.1 ],[ 379.43671993647547,53.1 ],[ 383.9179783039084,53.1 ],[ 389.11007513295664,53.1 ],[ 390.890398248277,0.0 ],[ 394.89247550840884,0.0 ],[ 394.9660933012399,0.0 ],[ 396.06148849760496,0.0 ],[ 396.50888123741737,0.0 ],[ 399.03561325612543,0.0 ],[ 399.42079299492036,0.0 ],[ 399.81277414168574,0.0 ],[ 400.0951984148409,0.0 ],[ 401.27140453784176,0.0 ],[ 402.9323766648583,0.0 ],[ 404.6013065876487,0.0 ],[ 407.7474317842159,0.0 ],[ 408.81716148023975,0.0 ],[ 409.3315360274096,0.0 ],[ 411.69628351097305,0.0 ],[ 413.38400103945776,0.0 ],[ 414.0779482413079,0.0 ],[ 415.3154081126925,0.0 ],[ 417.2383231199797,0.0 ],[ 419.79520794966,0.0 ],[ 420.5788606939525,0.0 ],[ 421.04169309023894,0.0 ],[ 421.91539849946287,0.0 ],[ 422.65945858731516,0.0 ],[ 424.86952445179276,0.0 ],[ 425.8202580296356,0.0 ],[ 428.01554256263705,0.0 ],[ 429.4289916428959,0.0 ],[ 430.60679683093144,0.0 ],[ 433.00223747637193,0.0 ],[ 434.30444660186964,0.0 ],[ 436.48082713787255,0.0 ],[ 445.29659580492523,0.0 ],[ 453.3412284287866,0.0 ],[ 457.5099646442263,0.0 ],[ 468.7392275498019,0.0 ],[ 473.8909262570842,0.0 ],[ 477.59467550687566,0.0 ],[ 482.37501802845975,0.0 ],[ 492.1436738635266,0.0 ],[ 502.21478986784484,0.0 ],[ 511.45451751073523,0.0 ],[ 522.9783213319408,53.1 ],[ 528.426145769594,53.1 ],[ 543.0396767191364,53.1 ],[ 547.8166797176732,53.1 ],[ 552.993692482276,53.1 ],[ 558.0240115053475,53.1 ],[ 563.3956529131051,53.1 ],[ 568.6644730206013,53.1 ],[ 575.497524449002,53.1 ],[ 580.456863971335,53.1 ],[ 585.9948732365522,53.1 ],[ 591.4256231915904,53.1 ],[ 606.9699845966435,53.1 ],[ 618.3517719766171,53.1 ],[ 629.7944569082468,53.1 ],[ 635.5206480317008,53.1 ],[ 646.2577334927753,53.1 ],[ 651.4153950302031,53.1 ],[ 657.7065477386654,53.1 ],[ 678.5712114740421,53.1 ],[ 683.7262801501231,53.1 ],[ 693.6066477626612,53.1 ],[ 713.4048271339173,53.1 ],[ 728.9535908418117,53.1 ],[ 738.9470608840559,53.1 ],[ 748.8604967215432,53.1 ],[ 753.5974915153677,53.1 ],[ 759.8110307817444,53.1 ],[ 771.3090633464088,53.1 ],[ 781.6918246084132,53.1 ],[ 787.1946634030671,53.1 ],[ 792.7635156714363,53.1 ],[ 809.6243842377924,53.1 ],[ 815.9085952206556,53.1 ],[ 821.8460102603915,53.1 ],[ 827.8113995884229,53.1 ],[ 845.8479725256267,53.1 ],[ 865.8884316413696,53.1 ],[ 871.0809749381593,53.1 ],[ 876.7676508324812,53.1 ],[ 882.2662355803151,53.1 ],[ 888.3641816818717,53.1 ],[ 904.943238749884,53.1 ],[ 910.831881410843,53.1 ],[ 916.0087090728987,53.1 ],[ 926.8838839824078,53.1 ],[ 939.1265258299235,53.1 ],[ 944.8364867255743,53.1 ],[ 950.3024548739087,53.1 ],[ 960.2752357906023,53.1 ],[ 969.3623803471902,53.1 ],[ 984.0173699358855,53.1 ],[ 990.1125647711564,53.1 ],[ 995.0894270629184,53.1 ],[ 1003.570276821474,53.1 ],[ 1008.6999499972203,53.1 ],[ 1014.1833849890514,53.1 ],[ 1020.4554853806511,53.1 ],[ 1033.5945024302464,53.1 ],[ 1046.583284682315,53.1 ],[ 1069.7782194450917,53.1 ],[ 1074.9248118284775,53.1 ],[ 1086.0147081539335,53.1 ],[ 1096.370695350741,53.1 ],[ 1105.497053628188,53.1 ],[ 1110.4188944605678,53.1 ],[ 1115.552901473459,53.1 ],[ 1126.1761311350033,53.1 ],[ 1131.0726713809886,53.1 ],[ 1136.0194470966305,53.1 ],[ 1146.2810185645483,53.1 ],[ 1156.0967924682748,53.1 ],[ 1160.4270554661314,53.1 ],[ 1181.0122984820052,53.1 ],[ 1186.6074552697196,53.1 ],[ 1192.2800437061828,53.1 ],[ 1196.4053361753065,53.1 ],[ 1200.5777453631042,53.1 ],[ 1205.6358403116515,53.1 ],[ 1210.412388251367,53.1 ],[ 1214.5490599790937,53.1 ],[ 1224.091401809782,53.1 ],[ 1234.878937261706,53.1 ],[ 1240.4420727154666,53.1 ],[ 1245.4085821738481,53.1 ],[ 1250.9703421733855,53.1 ],[ 1255.773105030396,53.1 ],[ 1271.9590744573409,53.1 ],[ 1307.4784485064708,53.1 ],[ 1326.9758968770218,53.1 ],[ 1341.1779799152841,53.1 ],[ 1356.0151959543862,53.1 ],[ 1365.9904236415064,53.1 ],[ 1376.8566741021211,53.1 ],[ 1385.7060076795676,53.1 ],[ 1395.6497548471523,53.1 ],[ 1400.6869160571669,53.1 ],[ 1416.107127324211,53.1 ],[ 1427.1371245564064,53.1 ],[ 1432.6274160711957,53.1 ],[ 1436.896427512249,53.1 ],[ 1447.1003299304336,53.1 ],[ 1452.4441268858616,53.1 ],[ 1457.6596253157556,53.1 ],[ 1467.2548654994205,53.1 ],[ 1471.6042021067694,53.1 ],[ 1475.9130755518772,53.1 ],[ 1486.8097291124507,53.1 ],[ 1492.0559895113727,53.1 ],[ 1507.5462074868933,53.1 ],[ 1512.8608805614278,53.1 ],[ 1523.6603726549174,53.1 ],[ 1533.9060104190316,53.1 ],[ 1543.9824927897102,53.1 ],[ 1549.0227640497312,53.1 ],[ 1553.803853834565,53.1 ],[ 1559.2086695565463,53.1 ],[ 1570.173544739152,53.1 ],[ 1574.6715638006551,53.1 ],[ 1579.885733854503,53.1 ],[ 1590.577901685838,53.1 ],[ 1596.3145177444262,53.1 ],[ 1600.8558945927502,53.1 ],[ 1613.4460484651488,53.1 ],[ 1619.534194765949,53.1 ],[ 1624.857762297751,53.1 ],[ 1629.4915520874597,53.1 ],[ 1634.5453873253991,53.1 ],[ 1638.5779245005415,53.1 ],[ 1649.537407855505,53.1 ],[ 1654.0391995944237,53.1 ],[ 1658.5719959311643,53.1 ],[ 1661.6165196012284,53.1 ],[ 1667.5419477468138,53.1 ],[ 1685.3183223022725,53.1 ],[ 1691.5023044965617,53.1 ],[ 1703.8341662503276,53.1 ],[ 1716.0471322831697,53.1 ],[ 1728.7319791483285,53.1 ],[ 1739.8573500856944,53.1 ],[ 1762.5330849161394,53.1 ],[ 1781.0396199245436,53.1 ],[ 1792.5083747972212,53.1 ],[ 1808.7944532271265,53.1 ],[ 1812.809637383863,53.1 ],[ 1817.4756181109,53.1 ],[ 1822.9445324125318,53.1 ],[ 1832.881435448665,53.1 ],[ 1843.9571441649366,53.1 ],[ 1864.2384270524437,53.1 ],[ 1873.2530537752077,53.1 ],[ 1882.6717734945394,53.1 ],[ 1892.3237541605756,53.1 ],[ 1899.0121419753887,53.1 ],[ 1911.5203328835769,53.1 ],[ 1917.5619258023628,53.1 ],[ 1936.431418000061,53.1 ],[ 1942.4551095734298,53.1 ],[ 1953.7638430431416,53.1 ],[ 1958.906158178558,53.1 ],[ 1964.1012037365706,53.1 ],[ 1968.9014379666778,53.1 ],[ 1973.97208351152,53.1 ],[ 1984.1673852760114,53.1 ],[ 1998.7052283871558,53.1 ],[ 2009.3140606238928,53.1 ],[ 2019.955984138742,53.1 ],[ 2035.2015521770072,53.1 ],[ 2050.485029438044,53.1 ],[ 2060.816844478568,53.1 ],[ 2065.7294893230755,53.1 ],[ 2070.1981104140377,53.1 ],[ 2075.0054008194015,53.1 ],[ 2079.829232227895,53.1 ],[ 2091.1207589981204,53.1 ],[ 2097.534430578104,53.1 ],[ 2108.6375965028656,53.1 ],[ 2120.3309762526146,53.1 ],[ 2143.8763610769643,53.1 ],[ 2155.3716035335965,53.1 ],[ 2160.9525894573235,53.1 ],[ 2172.6219438713674,53.1 ],[ 2193.5761873493716,53.1 ],[ 2215.4284941076735,53.1 ],[ 2225.386298105246,53.1 ],[ 2236.9252426440144,53.1 ],[ 2242.607115957887,53.1 ],[ 2255.4043255445376,53.1 ],[ 2266.98007738993,53.1 ],[ 2276.0973803838265,53.1 ],[ 2281.2025172228377,53.1 ],[ 2292.338349590001,53.1 ],[ 2304.636079919513,53.1 ],[ 2314.6525945326134,53.1 ],[ 2320.202017577785,53.1 ],[ 2325.3805566295077,53.1 ],[ 2337.575610766734,53.1 ],[ 2348.237945209788,53.1 ],[ 2359.8900902471987,53.1 ],[ 2364.2241740147915,53.1 ],[ 2368.702409780117,53.1 ],[ 2379.739538414029,53.1 ],[ 2385.4290129838055,53.1 ],[ 2396.7886919554667,53.1 ],[ 2407.732998206462,53.1 ],[ 2423.3409953058303,53.1 ],[ 2428.8235789238865,53.1 ],[ 2434.1102855677696,53.1 ],[ 2442.658267754097,53.1 ],[ 2453.7235598202697,53.1 ],[ 2464.9418078601984,53.1 ],[ 2470.24824388471,53.1 ],[ 2481.7551069315045,53.1 ],[ 2492.043100702939,53.1 ],[ 2497.233932404915,53.1 ],[ 2503.452542937787,53.1 ],[ 2514.2996306299037,53.1 ],[ 2525.730998952812,53.1 ],[ 2530.4865696456004,53.1 ],[ 2535.59348757639,53.1 ],[ 2546.13210824171,53.1 ],[ 2556.331643771224,53.1 ],[ 2578.0850074913133,53.1 ],[ 2584.0677620468127,53.1 ],[ 2589.9804477710845,53.1 ],[ 2601.5271546895187,53.1 ],[ 2612.817662290273,53.1 ],[ 2626.546162680004,53.1 ],[ 2643.97426719127,53.1 ],[ 2662.6109971491696,53.1 ],[ 2674.861831181227,53.1 ],[ 2686.8919057658354,53.1 ],[ 2692.70445008092,53.1 ],[ 2697.8716421864156,53.1 ],[ 2714.7293087272074,53.1 ],[ 2725.8677020335467,53.1 ],[ 2744.424296997053,53.1 ],[ 2755.460388510536,53.1 ],[ 2761.2176977867807,53.1 ],[ 2766.1990252939568,53.1 ],[ 2771.736417749782,53.1 ],[ 2782.3837311784196,53.1 ],[ 2787.772450531128,53.1 ],[ 2792.9399718252744,53.1 ],[ 2804.9584755707533,53.1 ],[ 2816.7236789871713,53.1 ],[ 2827.508117266638,53.1 ],[ 2840.363214527446,53.1 ],[ 2847.164684060797,53.1 ],[ 2853.84364540004,53.1 ],[ 2871.456430081595,53.1 ],[ 2881.532843678127,53.1 ],[ 2891.8047986248575,53.1 ],[ 2902.7324399360664,53.1 ],[ 2913.4079007591554,53.1 ],[ 2929.6784219771703,53.1 ],[ 2941.570027374428,53.1 ],[ 2954.387079400881,53.1 ],[ 2965.6819206044233,53.1 ],[ 2972.161133416375,53.1 ],[ 2976.008042012663,53.1 ],[ 2980.649202189644,53.1 ],[ 2985.676347297929,53.1 ],[ 2990.5023687648813,53.1 ],[ 2995.517312991183,53.1 ],[ 3009.516343821631,53.1 ],[ 3015.600678424966,53.1 ],[ 3021.2215825981602,53.1 ],[ 3030.3183431408916,53.1 ],[ 3034.849258808895,53.1 ],[ 3044.0401069485565,53.1 ],[ 3048.8375727744224,53.1 ],[ 3058.4215211516494,53.1 ],[ 3063.1053005898148,53.1 ],[ 3068.410440394638,53.1 ],[ 3076.3476327290427,53.1 ],[ 3081.0736281233735,53.1 ],[ 3085.5833067897715,53.1 ],[ 3090.5924312625725,53.1 ],[ 3096.070815151545,53.1 ],[ 3112.598237414052,53.1 ],[ 3117.2091356537935,53.1 ],[ 3127.0983288750476,53.1 ],[ 3131.824373943611,53.1 ],[ 3142.724310861831,53.1 ],[ 3147.905569047183,53.1 ],[ 3153.5951119145006,53.1 ],[ 3163.133230518048,53.1 ],[ 3171.890169028947,53.1 ],[ 3182.850444316506,53.1 ],[ 3194.542130785371,53.1 ],[ 3205.592703605019,53.1 ],[ 3210.4344532464725,53.1 ],[ 3216.1863207003234,53.1 ],[ 3221.5850249101127,53.1 ],[ 3230.966832908016,53.1 ],[ 3240.687003590248,53.1 ],[ 3252.205933296147,53.1 ],[ 3264.4046633995645,53.1 ],[ 3270.889908378847,53.1 ],[ 3280.297405684337,53.1 ],[ 3291.9837818331584,53.1 ],[ 3296.6773701217057,53.1 ],[ 3301.659850521227,53.1 ],[ 3311.0872969424195,53.1 ],[ 3315.9634768738024,53.1 ],[ 3321.334287117461,53.1 ],[ 3331.354996539008,53.1 ],[ 3335.5501898623556,53.1 ],[ 3340.572586511851,53.1 ],[ 3351.42097446257,53.1 ],[ 3357.512658687775,53.1 ],[ 3369.473316928653,53.1 ],[ 3376.003359403247,53.1 ],[ 3382.3098102833633,53.1 ],[ 3390.0858000897315,53.1 ],[ 3396.7644438530597,53.1 ],[ 3403.399509646791,53.1 ],[ 3414.981366476946,53.1 ],[ 3421.0161139947213,53.1 ],[ 3432.108995987495,53.1 ],[ 3437.2426764649003,53.1 ],[ 3443.1803524724787,53.1 ],[ 3454.4976539431946,53.1 ],[ 3459.512261059621,53.1 ],[ 3464.767906417999,53.1 ],[ 3470.6868828300967,53.1 ],[ 3476.602310149784,53.1 ],[ 3482.646818056555,53.1 ],[ 3490.1593659744003,53.1 ],[ 3497.191326412656,53.1 ],[ 3504.50764055725,53.1 ],[ 3511.3402530821586,53.1 ],[ 3522.647490746332,53.1 ],[ 3527.7778629534373,53.1 ],[ 3533.404694066675,53.1 ],[ 3539.6165315042144,53.1 ],[ 3545.780585776491,53.1 ],[ 3557.69666305323,53.1 ],[ 3568.70822347019,53.1 ],[ 3574.0449815393185,53.1 ],[ 3584.455860607034,53.1 ],[ 3588.4213822981674,53.1 ],[ 3593.4681153450697,53.1 ],[ 3603.621874465639,53.1 ],[ 3608.683008639259,53.1 ],[ 3632.005256175269,53.1 ],[ 3642.6660371023872,53.1 ],[ 3648.2530412515725,53.1 ],[ 3654.52532049218,53.1 ],[ 3661.017564360271,53.1 ],[ 3667.2863892177998,53.1 ],[ 3673.653286131747,53.1 ],[ 3678.8368765193695,53.1 ],[ 3683.131472989884,53.1 ],[ 3689.185171089931,53.1 ],[ 3694.3515515175363,53.1 ],[ 3699.538266276958,53.1 ],[ 3705.1785417780166,53.1 ],[ 3714.92212016958,53.1 ],[ 3730.2295150065256,53.1 ],[ 3752.1359467440398,53.1 ],[ 3761.3642228427793,53.1 ],[ 3771.524121351785,53.1 ],[ 3776.9687683865723,53.1 ],[ 3782.3701202011057,53.1 ],[ 3792.8033655969634,53.1 ],[ 3797.8628414960535,53.1 ],[ 3802.2508286078705,53.1 ],[ 3815.1526381053395,53.1 ],[ 3818.7228893394963,53.1 ],[ 3827.9647066018224,53.1 ],[ 3832.916761725411,53.1 ],[ 3837.263431045412,53.1 ],[ 3842.0508442295823,53.1 ],[ 3846.423690509612,53.1 ],[ 3851.288914671729,53.1 ],[ 3858.9924088835505,53.1 ],[ 3862.5343126590906,53.1 ],[ 3874.2269959666714,53.1 ],[ 3882.3266158668025,53.1 ],[ 3886.5647314145226,53.1 ],[ 3891.6365833037985,53.1 ],[ 3901.20281682961,53.1 ],[ 3911.6074140267187,53.1 ],[ 3920.00548997862,53.1 ],[ 3928.6784308458386,53.1 ],[ 3932.592135221783,53.1 ],[ 3946.040733562137,53.1 ],[ 3950.5236267682853,53.1 ],[ 3955.7369292915614,53.1 ],[ 3965.3143539498788,53.1 ],[ 3969.544544457335,53.1 ],[ 3982.5006704354537,53.1 ],[ 3987.3225052077782,53.1 ],[ 3992.182220916725,53.1 ],[ 3997.5392354653454,53.1 ],[ 4003.334859111742,53.1 ],[ 4009.281849415638,53.1 ],[ 4031.016502548809,53.1 ],[ 4039.824238949878,53.1 ],[ 4044.5796388295253,53.1 ],[ 4050.3809173073605,53.1 ],[ 4056.7012095735477,53.1 ],[ 4068.4540019779433,53.1 ],[ 4074.600930984235,53.1 ],[ 4086.897227174995,53.1 ],[ 4113.8344563123865,53.1 ],[ 4120.085754415143,53.1 ],[ 4120.085754415143,53.1 ],[ 4138.798808666939,53.1 ],[ 4147.9203731048665,53.1 ],[ 4151.777827421281,53.1 ],[ 4156.07302046199,53.1 ],[ 4156.973965900599,53.1 ],[ 4159.623925310569,53.1 ],[ 4163.1756517452095,53.1 ],[ 4164.265368290691,0.0 ],[ 4164.9620950831895,0.0 ],[ 4165.176761901848,0.0 ],[ 4166.041503391961,0.0 ],[ 4168.803738925309,0.0 ],[ 4170.530932689598,0.0 ],[ 4172.318019656523,0.0 ],[ 4174.619045233232,0.0 ],[ 4176.302451531376,0.0 ],[ 4178.5338958530365,0.0 ],[ 4181.475835238351,0.0 ],[ 4185.291812576477,0.0 ],[ 4188.866925069642,0.0 ],[ 4193.177908807393,0.0 ],[ 4203.0927332859565,0.0 ],[ 4213.386481390282,0.0 ],[ 4222.212992374711,0.0 ],[ 4226.476988141031,0.0 ],[ 4235.124941812997,0.0 ],[ 4239.872991853678,0.0 ],[ 4248.815855357306,0.0 ],[ 4253.52566828204,53.1 ],[ 4258.390852621446,53.1 ],[ 4263.40451698408,53.1 ],[ 4273.192093646099,53.1 ],[ 4282.5989734612585,53.1 ],[ 4291.661478035127,53.1 ],[ 4295.867470361769,53.1 ],[ 4304.414142494116,53.1 ],[ 4313.620872289506,53.1 ],[ 4318.016817471868,53.1 ],[ 4332.38210359815,53.1 ],[ 4336.369069669354,53.1 ],[ 4345.625291434266,53.1 ],[ 4354.521553091781,53.1 ],[ 4359.602432797242,53.1 ],[ 4368.442150415735,53.1 ],[ 4374.047162501575,53.1 ],[ 4383.197204373065,53.1 ],[ 4400.150657761293,53.1 ],[ 4403.219353312974,53.1 ],[ 4413.181813210174,53.1 ],[ 4418.952065513698,53.1 ],[ 4424.737393739459,53.1 ],[ 4430.531692132887,53.1 ],[ 4436.560983677541,53.1 ],[ 4441.350909454282,53.1 ],[ 4451.871219515977,53.1 ],[ 4456.125510068251,53.1 ],[ 4461.308629549206,53.1 ],[ 4465.874579360404,53.1 ],[ 4470.432593275441,53.1 ],[ 4474.3961874045945,53.1 ],[ 4478.516863586354,53.1 ],[ 4488.829182559423,53.1 ],[ 4494.010210026887,53.1 ],[ 4498.700496000728,53.1 ],[ 4519.630568701785,53.1 ],[ 4530.041408076919,53.1 ],[ 4549.450138414461,53.1 ],[ 4554.884107551977,53.1 ],[ 4574.115218606111,53.1 ],[ 4579.344796745828,53.1 ],[ 4583.964824125679,53.1 ],[ 4600.254345108972,53.1 ],[ 4605.373313276977,53.1 ],[ 4615.024250564529,53.1 ],[ 4628.271400366613,53.1 ],[ 4632.601205702116,53.1 ],[ 4641.940830402807,53.1 ],[ 4647.689098223198,53.1 ],[ 4652.595389109711,53.1 ],[ 4657.9273575474235,53.1 ],[ 4672.672187059547,53.1 ],[ 4686.8976003180705,53.1 ],[ 4692.004802965959,53.1 ],[ 4697.0749862054145,53.1 ],[ 4707.391458658509,53.1 ],[ 4712.312421394333,53.1 ],[ 4717.815687557015,53.1 ],[ 4723.367799970961,53.1 ],[ 4734.32765002157,53.1 ],[ 4739.414139950119,53.1 ],[ 4745.270275827606,53.1 ],[ 4753.845695845204,53.1 ],[ 4758.039870421037,53.1 ],[ 4762.627813330818,53.1 ],[ 4767.648810689594,53.1 ],[ 4771.891332212912,53.1 ],[ 4776.719243769142,53.1 ],[ 4781.961292786325,53.1 ],[ 4785.4794271860765,53.1 ],[ 4788.987662030582,53.1 ],[ 4792.821068123206,53.1 ],[ 4796.996444711028,53.1 ],[ 4806.937295466038,53.1 ],[ 4811.302623655613,53.1 ],[ 4814.675831736406,53.1 ],[ 4822.822385813729,53.1 ],[ 4826.010011753273,0.0 ],[ 4841.9059581126385,0.0 ],[ 4851.546956768257,0.0 ],[ 4859.527861566998,0.0 ],[ 4863.871176721507,0.0 ],[ 4867.769055469043,0.0 ],[ 4875.854508862562,0.0 ],[ 4883.509074938907,0.0 ],[ 4900.41085163757,0.0 ],[ 4904.089788948477,0.0 ],[ 4930.088562534527,0.0 ],[ 4942.66190464122,0.0 ],[ 4954.975405928333,0.0 ],[ 4963.495145882513,0.0 ],[ 4973.090451385486,0.0 ],[ 4980.66118060696,0.0 ],[ 4991.856822926967,0.0 ],[ 4995.635205863601,0.0 ],[ 5012.178747331334,0.0 ],[ 5017.094670752444,0.0 ],[ 5021.895006346619,53.1 ],[ 5028.9636576074245,53.1 ],[ 5034.246190855701,53.1 ],[ 5038.540653044389,53.1 ],[ 5044.32139887145,53.1 ],[ 5054.725408117883,53.1 ],[ 5065.278141899048,53.1 ],[ 5071.272046564452,53.1 ],[ 5076.231652078908,53.1 ],[ 5089.877181211685,53.1 ],[ 5102.657971913545,53.1 ],[ 5108.14304293381,53.1 ],[ 5112.620436953741,53.1 ],[ 5115.673578897662,53.1 ],[ 5117.789649789614,53.1 ],[ 5119.5395179129,53.1 ],[ 5120.503090913673,0.0 ],[ 5121.0152138307685,0.0 ],[ 5121.819189012008,0.0 ],[ 5124.063406942363,0.0 ],[ 5124.604572776118,0.0 ],[ 5125.333994795588,0.0 ],[ 5128.204826784708,0.0 ],[ 5130.197871329814,0.0 ],[ 5133.1925581237665,0.0 ],[ 5133.48701224875,0.0 ],[ 5134.322043138916,0.0 ],[ 5134.995078187496,0.0 ],[ 5136.440924594356,0.0 ],[ 5137.074701667954,0.0 ],[ 5139.150446200096,0.0 ],[ 5140.262774113347,0.0 ],[ 5140.859988422224,0.0 ],[ 5142.351326033824,0.0 ],[ 5144.831520599413,0.0 ],[ 5145.28258027321,0.0 ],[ 5146.10407107891,0.0 ],[ 5147.66494305362,0.0 ],[ 5149.063363475686,0.0 ],[ 5149.637869266041,0.0 ],[ 5150.709410177794,0.0 ],[ 5151.53762900148,0.0 ],[ 5151.729497267369,0.0 ],[ 5151.997845837134,0.0 ],[ 5154.853041125717,0.0 ],[ 5155.088203556005,0.0 ],[ 5155.940069307171,0.0 ],[ 5157.02522571146,0.0 ],[ 5157.748364118453,0.0 ],[ 5158.6435191525425,0.0 ],[ 5159.173489275565,0.0 ],[ 5160.049042860273,0.0 ],[ 5160.193989394369,0.0 ],[ 5162.510365811197,0.0 ],[ 5162.70689852226,0.0 ],[ 5163.440771896654,0.0 ],[ 5166.364586992945,0.0 ],[ 5167.431209526067,0.0 ],[ 5168.37248352115,0.0 ],[ 5168.598058660035,0.0 ],[ 5169.168408557766,0.0 ],[ 5170.648303844814,0.0 ],[ 5171.327067233357,0.0 ],[ 5174.136350553605,0.0 ],[ 5176.7109194494815,0.0 ],[ 5177.609934070559,0.0 ],[ 5178.455243015036,0.0 ],[ 5179.633872590002,0.0 ],[ 5183.271668982122,0.0 ],[ 5185.137041588455,0.0 ],[ 5196.218135785075,0.0 ],[ 5205.167685794566,0.0 ],[ 5209.891427166657,0.0 ],[ 5214.472128310662,0.0 ],[ 5223.016808810305,0.0 ],[ 5231.49991561661,0.0 ],[ 5236.295365087663,0.0 ],[ 5250.642172468975,0.0 ],[ 5260.756472909673,0.0 ],[ 5275.797040303109,0.0 ],[ 5285.203935096226,53.1 ],[ 5304.381080504697,53.1 ],[ 5309.27856104194,53.1 ],[ 5328.024315619961,53.1 ],[ 5336.8810006273725,53.1 ],[ 5358.934713417021,53.1 ],[ 5368.161761471716,53.1 ],[ 5371.790879471176,53.1 ],[ 5379.063164124161,53.1 ],[ 5383.204819761245,53.1 ],[ 5388.941907777316,53.1 ],[ 5393.874065243032,53.1 ],[ 5400.703278746446,53.1 ],[ 5411.868255027515,53.1 ],[ 5426.679